# Generated by Django 3.1.5 on 2021-01-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=40)),
                ('voice', models.FileField(blank=True, upload_to='sounds/')),
            ],
        ),
    ]
